### ISSUE TITLE
The simdjson builds import all dependencies by default (SIMDJSON_COMPETITION)

### ISSUE THREAD

**Issue by lemire** [simdjson/cmakedemo#1]
It is somewhat annoying to have to force SIMDJSON_COMPETITION to be off.

https://github.com/simdjson/cmakedemo/blob/c674b07eecc4c967abdb27c309fc9aedebbea097/dependencies/CMakeLists.txt#L17

**Comment by lemire** [comment]
cc @jkeiser

**Comment by jkeiser** [comment]
Yeah, we should default it to ON at this point. It originally caused make to take longer than one would like due to building gbench's tests as well as our benchmarks, but that's fixed.

**Comment by lemire** [comment]
I think you have the wrong variable. You are thinking of GOOGLE_BENCHMARK or something, I refer to SIMDJSON_COMPETITION.

**Comment by jkeiser** [comment]
Oh! Yes. Though even this one is not that slow ... the recent changes I made make it so that you don't pay the cost until and unless you build the competition executables (for most of them). I think we could default this one to ON as well now.

**Comment by jkeiser** [comment]
Never mind. I get what you are saying. Deleting comment.
